name: Build and Publish Package

on:
  push:
    branches:
      - master

env:
  NODE_VERSION: 14.x
       
jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: Install dependencies
        run: |
          if [ -e npm.lock ]; then
          npm install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
          
      - name: Build project
        run: npm run build
        
      - name: Deploy 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-2
        run: |
          aws s3 cp \
            --recursive \
            dist s3://vms-s3-devops/node/linux
            
  window-build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: Install dependencies
        run: |
          if (-e $npm.lock) {then
          npm install --frozen-lockfile }
          elif (-e $package-lock.json) {then
          npm ci }
          { else 
          npm i
          fi }
          
      - name: Build project
        run: npm run build
        
      - name: Deploy 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-2
        run: |
          aws s3 cp \
            --recursive \
            dist s3://vms-s3-devops/node/window

